/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * variantAnalyzerWindow.java
 *
 * Created on Jul 19, 2011, 9:38:42 AM
 */

package org.me.main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;


/**
 *
 * @author salvo
 */
public class variantAnalyzerWindow extends javax.swing.JFrame {

    String inputFile, annotationFolder, sequencesFolder, outputFolder;
    int numberOfNucleotides;
    static Process p;
    static BufferedReader reader;
    String command;
    String annotationFile;
    String status="";
   


    /** Creates new form variantAnalyzerWindow */
    public variantAnalyzerWindow() {

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Polymorphysm Analyzer");
        setResizable(false);

        jTextField1.setEditable(false);
        jTextField1.setText("Select input file....");
        jTextField1.setPreferredSize(new java.awt.Dimension(67, 40));

        jButton1.setText("Open File");
        jButton1.setMaximumSize(new java.awt.Dimension(400, 400));
        jButton1.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setText("Select annotation file....");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setText("Select sequences folder....");

        jButton2.setText("Open File");
        jButton2.setMaximumSize(new java.awt.Dimension(200, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Choose Folder");
        jButton3.setMaximumSize(new java.awt.Dimension(300, 300));
        jButton3.setPreferredSize(new java.awt.Dimension(300, 300));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setText("Run");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Verbouse output");

        jButton9.setText("Exit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Parameters"));

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("2");

        jLabel1.setText("Minimum coverage to call base");

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0.05");

        jLabel2.setText("p-Value cut-off for SNP calling");

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0.05");

        jLabel3.setText("p-Value cut-off for INDEL calling");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, 0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser loader = new JFileChooser();
        loader.showOpenDialog(variantAnalyzerWindow.this);
        File f1 = loader.getSelectedFile();
        inputFile = f1.getAbsolutePath();
        jTextField1.setText(f1.getParent() + "/" + loader.getName(f1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser loader = new JFileChooser();
        loader.showOpenDialog(variantAnalyzerWindow.this);
        File f1 = loader.getSelectedFile();
        annotationFile = f1.getAbsolutePath();
        jTextField3.setText(f1.getParent() + "/" + loader.getName(f1));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser loader = new JFileChooser();
        loader.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        loader.showOpenDialog(variantAnalyzerWindow.this);
        File f1 = loader.getSelectedFile();
        sequencesFolder = f1.getAbsolutePath() +"/";
        jTextField4.setText(f1.getParent() + "/" + f1.getName());
    }//GEN-LAST:event_jButton3ActionPerformed




    private  class runCommand implements Runnable {
        public void run() {
                             if (jTextField1.getText().equals("Select input file...."))
                             JOptionPane.showMessageDialog(null ,"       Please choose a valid file!       ", "Warning!!", JOptionPane.ERROR_MESSAGE );
                             else
                            {
                                 try{
                                        p=Runtime.getRuntime().exec(command);
           
                                     }catch (IOException e)
                                        {
                                            System.out.println("exception happened - here's what I know: ");
                                            e.printStackTrace();
                                            System.exit(-1);
                                        }

                            }
                         }
    }


    private  class checkSequencesFile implements Runnable {
        public void run() {
                            String command2 = "xterm -e ./checkSequenceFolder " + jTextField4.getText();

                            if (jTextField4.getText().equals("Select sequences folder...."))
                             JOptionPane.showMessageDialog(null ,"       Please choose a valid folder!       ", "Warning!!", JOptionPane.ERROR_MESSAGE );
                            else
                             {
                                 try{
                                         p=Runtime.getRuntime().exec(command2);

                                     }catch (IOException e)
                                     {
                                        System.out.println("exception happened - here's what I know: ");
                                        e.printStackTrace();
                                        System.exit(-1);
                                      }

                             }
                        }
    }


      private  class checkInputFile implements Runnable {
        public void run() {
                            String command2 = "xterm -e ./checkInputFile " + jTextField1.getText() + " " + jTextField3.getText();

                            if (jTextField3.getText().equals("Select annotation folder....") || jTextField1.getText().equals("Select input file...."))
                            JOptionPane.showMessageDialog(null ,"       Please choose valid input file/annotation folder!       ", "Warning!!", JOptionPane.ERROR_MESSAGE );
                            else
                            {
                            try{
                                    p=Runtime.getRuntime().exec(command2);

                                }catch (IOException e)
                                    {
                                        System.out.println("exception happened - here's what I know: ");
                                        e.printStackTrace();
                                        System.exit(-1);
                                    }

                            }
                        }
    }




     private  class checkAnnotationFiles implements Runnable {
        public void run() {
                                 String command2 = "xterm -e ./checkAnnotationFolder " + jTextField3.getText();

                                if (jTextField3.getText().equals("Select annotation folder...."))
                                JOptionPane.showMessageDialog(null ,"       Please choose a valid folder!       ", "Warning!!", JOptionPane.ERROR_MESSAGE );
                                else
                                {
                                    try{
                                            p=Runtime.getRuntime().exec(command2);

                                       }catch (IOException e)
                                            {
                                                System.out.println("exception happened - here's what I know: ");
                                                e.printStackTrace();
                                                System.exit(-1);
                                            }

                                }
                        }

    }


    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       
        //Check every field is correctely filled
         int checkAllFields = 1;
         
        if(jTextField1.getText().equals("Select input file...."))
        {
            JOptionPane.showMessageDialog(null, "       Please choose a valid input file!       ", "Warning!!", JOptionPane.ERROR_MESSAGE);
            checkAllFields=0;
        }

        if(jTextField3.getText().equals("Select annotation file...."))
        {
            JOptionPane.showMessageDialog(null, "       Please choose a valid annotation file!       ", "Warning!!", JOptionPane.ERROR_MESSAGE);
            checkAllFields=0;
        }

        if(jTextField4.getText().equals("Select sequences folder...."))
        {
            JOptionPane.showMessageDialog(null, "       Please choose a valid sequences folder!       ", "Warning!!", JOptionPane.ERROR_MESSAGE);
            checkAllFields=0;
        }

        
        for (int i = 0; i < jTextField2.getText().length(); i++)
        {
             if (!Character.isDigit(jTextField2.getText().charAt(i)))
             {
                  JOptionPane.showMessageDialog(null, "      Minimum coverage must be numerical!       ", "Warning!!", JOptionPane.ERROR_MESSAGE);
                  checkAllFields=0;
             }
        }
        
        
        for (int i = 0; i < jTextField5.getText().length(); i++)
        {
             if (!Character.isDigit(jTextField5.getText().charAt(i)) && jTextField5.getText().charAt(i)!='.')
             {
                  JOptionPane.showMessageDialog(null, "      SNP p-Value must be numerical!       ", "Warning!!", JOptionPane.ERROR_MESSAGE);
                  checkAllFields=0;
             }
        }
        
        
        for (int i = 0; i < jTextField6.getText().length(); i++)
        {
             if (!Character.isDigit(jTextField6.getText().charAt(i)) && jTextField5.getText().charAt(i)!='.')
             {
                  JOptionPane.showMessageDialog(null, "      INDEL p-Value must be numerical!       ", "Warning!!", JOptionPane.ERROR_MESSAGE);
                  checkAllFields=0;
             }
        } 
        
        
        if (checkAllFields==1)
        {
            command = "xterm -e ./bin/variantAnalyzer/Debug/variantAnalyzer " + inputFile + " " + annotationFile + " " + sequencesFolder ;
            if(jCheckBox1.isSelected())  command += " 1 ";
            else command += " 0 ";
            command += " " + jTextField2.getText() + " " + jTextField5.getText() + " " + jTextField6.getText();
            
            //JOptionPane.showMessageDialog(null, command, "Warning!!", JOptionPane.ERROR_MESSAGE);
            Thread t = new Thread(new runCommand());
            t.start();
        }
	
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField3ActionPerformed

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new variantAnalyzerWindow().setVisible(true);

            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
